### ISSUE TITLE
Not exclusive to base64

### ISSUE THREAD

**Issue by fregante** [javierbyte/base64-image-utils#1]
These methods work with any accessible URI, it might be a good idea to mention it somewhere or maybe even change the name

**Comment by javierbyte** [comment]
Yeah! They do! haha

I was working on another project where I only had base64, and then I created this repo based on that implementation and forgot that it is simply `img.src`. Thanks! Yeah, we should change the name. What about `image-data-utils`?

**Comment by fregante** [comment]
It depends on whether you want to expand this package or just keep it as a single-function module (to which I'm always for). I thought of a code simplification if that's the case
